In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from langdetect import detect
from deep_translator import GoogleTranslator

In [2]:
df = pd.read_csv('tasks 2\\articles.csv')

In [3]:
df.head(20)

,datetime,title,source,link,content
0,1/6/2014 6:49:36 AM,Nvidia CEO talks up mobile chips with brawny P...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
1,4/23/2014 11:26:52 PM,Ex-Nvidia manager settles U.S. SEC charges on ...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
2,6/1/2015 5:31:48 AM,Nvidia says it sees revenue from cloud computi...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
3,1/5/2016 6:03:35 AM,Nvidia says Volvo is first customer for new au...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
4,9/28/2016 3:10:26 PM,BRIEF-Nvidia and TomTom develop mapping system...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
5,9/29/2016 2:30:22 PM,Car industry puts cooperation on show in battl...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
6,9/29/2016 7:20:23 PM,UPDATE 1-Car industry shows off cooperation as...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
7,9/29/2016 10:20:22 PM,Udacity's self-driving car engineering degree ...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
8,9/30/2016 10:10:23 PM,Qualcomm to fight EU antitrust charge at Nov. ...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
9,10/14/2016 7:20:27 AM,BRIEF-Nvidia enters into credit agreement to r...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
10,10/14/2016 1:40:28 PM,"IBM, Google, others to unveil new open interfa...",Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
11,10/18/2016 1:10:21 PM,BRIEF-Gaming Corps and NVIDIA sign deal for di...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
12,10/20/2016 12:56:20 PM,UPDATE 2-Tesla says self-driving hardware to b...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
13,10/20/2016 12:56:20 PM,Tesla says self-driving hardware to be built i...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
14,11/10/2016 11:26:21 PM,Nvidia's quarterly revenue jumps 53.6 pct (NVDA),Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
15,11/10/2016 11:30:21 PM,BRIEF-Nvidia posts Q3 earnings per share $0.94...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
16,11/11/2016 1:28:17 AM,Self-driving car chipmaker Nvidia's shares sur...,Business Insider,https://markets.businessinsider.com/news/nvda-...,Content not found
17,11/14/2016 2:48:20 PM,Autonomous vehicle tech company AImotive posit...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
18,11/15/2016 9:20:21 PM,Elon Musk-backed AI startup and Microsoft sign...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found
19,12/2/2016 3:58:03 AM,BRIEF-NVIDIA's board amended and restated NVID...,Reuters,https://markets.businessinsider.com/news/nvda-...,Content not found

In [4]:
#drop the content column
df = df.drop(columns=['content']);

In [12]:
#check unique values in the source column
df['link'].unique()

array(['https://markets.businessinsider.com/news/nvda-stock?p=http://feeds.reuters.com/~r/reuters/businessNews/~3/zwHSNg_4zqs/story01.htm',
       'https://markets.businessinsider.com/news/nvda-stock?p=http://feeds.reuters.com/~r/reuters/businessNews/~3/xpV7GkX4WAw/story01.htm',
       'https://markets.businessinsider.com/news/nvda-stock?p=http://feeds.reuters.com/~r/reuters/businessNews/~3/PVjxuvBNo1Q/story01.htm',
       ...,
       'https://markets.businessinsider.com/news/nvda-stock?p=/news/stocks/google-challenges-nvidia-ceo-jensen-huang-on-the-future-of-quantum-computing-1034322042',
       'https://markets.businessinsider.com/news/nvda-stock?p=/news/stocks/broadcom-stock-avgo-surges-on-alphabet-s-75b-ai-spending-plans-1034322153',
       'https://markets.businessinsider.com/news/nvda-stock?p=/news/stocks/nvidia-selloff-on-deepseek-a-buying-opportunity-says-morgan-stanley-1034322140'],
      shape=(10410,), dtype=object)

In [6]:
#format the date column
# df['datetime'] = pd.to_datetime(df['datetime'], format='%Y-%m-%d')
#check data types of the datetime column
df.dtypes

datetime    object
title       object
source      object
link        object
dtype: object

In [9]:
# Convert object to datetime format
df["datetime"] = pd.to_datetime(df["datetime"], errors='coerce')
df.dtypes

datetime    datetime64[ns]
title               object
source              object
link                object
dtype: object

In [16]:
df['title'][4]

'BRIEF-Nvidia and TomTom develop mapping system for Self-Driving Cars (NVDA)'

In [17]:
df.head(20)

,datetime,title,source,link
0,2014-01-06 06:49:36,Nvidia CEO talks up mobile chips with brawny P...,Reuters,https://markets.businessinsider.com/news/nvda-...
1,2014-04-23 23:26:52,Ex-Nvidia manager settles U.S. SEC charges on ...,Reuters,https://markets.businessinsider.com/news/nvda-...
2,2015-06-01 05:31:48,Nvidia says it sees revenue from cloud computi...,Reuters,https://markets.businessinsider.com/news/nvda-...
3,2016-01-05 06:03:35,Nvidia says Volvo is first customer for new au...,Reuters,https://markets.businessinsider.com/news/nvda-...
4,2016-09-28 15:10:26,BRIEF-Nvidia and TomTom develop mapping system...,Reuters,https://markets.businessinsider.com/news/nvda-...
5,2016-09-29 14:30:22,Car industry puts cooperation on show in battl...,Reuters,https://markets.businessinsider.com/news/nvda-...
6,2016-09-29 19:20:23,UPDATE 1-Car industry shows off cooperation as...,Reuters,https://markets.businessinsider.com/news/nvda-...
7,2016-09-29 22:20:22,Udacity's self-driving car engineering degree ...,Reuters,https://markets.businessinsider.com/news/nvda-...
8,2016-09-30 22:10:23,Qualcomm to fight EU antitrust charge at Nov. ...,Reuters,https://markets.businessinsider.com/news/nvda-...
9,2016-10-14 07:20:27,BRIEF-Nvidia enters into credit agreement to r...,Reuters,https://markets.businessinsider.com/news/nvda-...
10,2016-10-14 13:40:28,"IBM, Google, others to unveil new open interfa...",Reuters,https://markets.businessinsider.com/news/nvda-...
11,2016-10-18 13:10:21,BRIEF-Gaming Corps and NVIDIA sign deal for di...,Reuters,https://markets.businessinsider.com/news/nvda-...
12,2016-10-20 12:56:20,UPDATE 2-Tesla says self-driving hardware to b...,Reuters,https://markets.businessinsider.com/news/nvda-...
13,2016-10-20 12:56:20,Tesla says self-driving hardware to be built i...,Reuters,https://markets.businessinsider.com/news/nvda-...
14,2016-11-10 23:26:21,Nvidia's quarterly revenue jumps 53.6 pct (NVDA),Reuters,https://markets.businessinsider.com/news/nvda-...
15,2016-11-10 23:30:21,BRIEF-Nvidia posts Q3 earnings per share $0.94...,Reuters,https://markets.businessinsider.com/news/nvda-...
16,2016-11-11 01:28:17,Self-driving car chipmaker Nvidia's shares sur...,Business Insider,https://markets.businessinsider.com/news/nvda-...
17,2016-11-14 14:48:20,Autonomous vehicle tech company AImotive posit...,Reuters,https://markets.businessinsider.com/news/nvda-...
18,2016-11-15 21:20:21,Elon Musk-backed AI startup and Microsoft sign...,Reuters,https://markets.businessinsider.com/news/nvda-...
19,2016-12-02 03:58:03,BRIEF-NVIDIA's board amended and restated NVID...,Reuters,https://markets.businessinsider.com/news/nvda-...