In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
from langdetect import detect
from deep_translator import GoogleTranslator

In [50]:
df = pd.read_csv('tasks 2\kilimall_appliances_listings.csv')

df.tail(15)

<>:1: SyntaxWarning: invalid escape sequence '\k'
<>:1: SyntaxWarning: invalid escape sequence '\k'
C:\Users\Administrator\AppData\Local\Temp\ipykernel_7488\201216582.py:1: SyntaxWarning: invalid escape sequence '\k'
  df = pd.read_csv('tasks 2\kilimall_appliances_listings.csv')

,product_name,product_type,product_description,price,link
675,MK TV Guard// FRIDGE Guard//A FREE 4 Way Exten...,appliances,NaN,"KSh 1,200",https://www.kilimall.co.ke/category/</listing/...
676,Hisense 20L Microwave Oven,appliances,NaN,"KSh 9,900",https://www.kilimall.co.ke/category/</listing/...
677,Dessini Multifunctional 8Litres Large Electric...,appliances,NaN,"KSh 6,800",https://www.kilimall.co.ke/category/</listing/...
678,Handheld Fan Mini Portable Fan USB Personal Fa...,appliances,NaN,KSh 499,https://www.kilimall.co.ke/category/</listing/...
679,Nunix POWERFUL Electric Deep FRYER + FREE EXT....,appliances,NaN,"KSh 9,869",https://www.kilimall.co.ke/category/</listing/...
680,4Pcs Anti Vibration Feet Pads Waterproof Legs ...,appliances,NaN,KSh 490,https://www.kilimall.co.ke/category/</listing/...
681,SWEEPER 3 IN 1 Smart Robot Vacuum Cleaner Auto...,appliances,NaN,"KSh 6,650",https://www.kilimall.co.ke/category/</listing/...
682,Nunix Easily Portable Dry Iron Box - White And...,appliances,NaN,KSh 920,https://www.kilimall.co.ke/category/</listing/...
683,Water Bottle Pump Water Dispensers USB Recharg...,appliances,NaN,KSh 559,https://www.kilimall.co.ke/category/</listing/...
684,"Sokany 300W Slow Masticating Juicer, Big 80mm ...",appliances,NaN,"KSh 7,300",https://www.kilimall.co.ke/category/</listing/...
685,4you Cordless Electric Kettle - 2L + Way Exten...,appliances,NaN,"KSh 1,245",https://www.kilimall.co.ke/category/</listing/...
686,Water Pump Food Grade Automatic Electric Water...,appliances,NaN,KSh 488,https://www.kilimall.co.ke/category/</listing/...
687,200AH RITAR HEAVY DUTY BATTERY,appliances,NaN,"KSh 23,999",https://www.kilimall.co.ke/category/</listing/...
688,CLEARANCE OFFER Electric Naifeo Immersion Hand...,appliances,NaN,"KSh 1,699",https://www.kilimall.co.ke/category/</listing/...
689,Kenwood Electric 7 Speed Hand Mixer,appliances,NaN,KSh 999,https://www.kilimall.co.ke/category/</listing/...

In [19]:
#removing the duplicates
df = df.drop_duplicates()

In [20]:
# Remove non-numeric characters
df["price"] = df["price"].str.replace(r"[^\d.]", "", regex=True)

In [48]:
df[10:50]

,product_name,product_type,product_description,price,link
10,"Nokia 105, 1.77"" screen, Dual SIM, Feature phone",phones-accessories,NaN,1115.0,https://www.kilimall.co.ke/category/listing/10...
11,"Luxurious look guaranteed for mobile phones,mo...",phones-accessories,NaN,158.0,https://www.kilimall.co.ke/category/listing/10...
12,RichRipple Y50 Pro Wireless Bluetooth Earphone...,phones-accessories,NaN,419.0,https://www.kilimall.co.ke/category/listing/18...
13,RichRipple 2 in 1 Smart Watch Men Women Blueto...,phones-accessories,NaN,1299.0,https://www.kilimall.co.ke/category/listing/21...
14,PAFEL Bluetooth selfie stick 3in1 phones tripo...,phones-accessories,NaN,329.0,https://www.kilimall.co.ke/category/listing/25...
15,4PCS Tripod Stand Ring Light Phones Selfie Sti...,phones-accessories,NaN,499.0,https://www.kilimall.co.ke/category/listing/20...
16,"Itel A70 128GB+8(3+5)GB RAM 6.6"" Screen 4G Net...",phones-accessories,NaN,9250.0,https://www.kilimall.co.ke/category/listing/29...
17,2024 New 3.5mm Wired Headphones In Ear Headset...,phones-accessories,NaN,189.0,https://www.kilimall.co.ke/category/listing/27...
18,"Silicone Suction Cup Phone Case Mount , Phone ...",phones-accessories,NaN,450.0,https://www.kilimall.co.ke/category/listing/10...
19,Mini Portable USB LED Book Light DC5V Ultra Br...,phones-accessories,NaN,189.0,https://www.kilimall.co.ke/category/listing/23...
20,VEDO F9 Bluetooth Earphone Mini True Wireless ...,phones-accessories,NaN,499.0,https://www.kilimall.co.ke/category/listing/20...
21,"Generic Ring Light Tripod 10Inch For Selfie,ma...",phones-accessories,NaN,1299.0,https://www.kilimall.co.ke/category/listing/24...
22,RichRipple Universal Foldable Mobile Phone Hol...,phones-accessories,NaN,229.0,https://www.kilimall.co.ke/category/listing/24...
23,Samsung 25 Watts Fast Charger Adapter for Gala...,phones-accessories,NaN,650.0,https://www.kilimall.co.ke/category/listing/10...
24,Refurbished oppo a37 Smartphone 100% original ...,phones-accessories,NaN,3199.0,https://www.kilimall.co.ke/category/listing/25...
25,[[New Year Promotion] Infinix Hot 50i 128GB + ...,phones-accessories,NaN,12750.0,https://www.kilimall.co.ke/category/listing/10...
26,Precision Screwdriver 115 In 1 Set Magnetic Sc...,phones-accessories,NaN,849.0,https://www.kilimall.co.ke/category/listing/29...
27,"Samsung Galaxy A16 128GB+4GB 6.7"" Super AMOLED...",phones-accessories,NaN,19499.0,https://www.kilimall.co.ke/category/listing/10...
28,New Arrival TECNO POP 9 128GB + 6(3+3)GB 4.5G ...,phones-accessories,NaN,11499.0,https://www.kilimall.co.ke/category/listing/10...
29,New i10 Pro Max Smart Watch 2.19' Smartwatches...,phones-accessories,NaN,999.0,https://www.kilimall.co.ke/category/listing/10...
30,Real 30000mAh Punk Style Super Fast Charging C...,phones-accessories,NaN,1699.0,https://www.kilimall.co.ke/category/listing/28...
31,New Year's promotion Air Pro 6 Bluetooth Wirel...,phones-accessories,NaN,499.0,https://www.kilimall.co.ke/category/listing/10...
32,RichRipple 60W 5 In 1 Multi-Functional Fast Ch...,phones-accessories,NaN,259.0,https://www.kilimall.co.ke/category/listing/30...
33,Refurbished OPPO A7 A5s smart phone 64GB+4GB 6...,phones-accessories,NaN,6599.0,https://www.kilimall.co.ke/category/listing/25...
34,6A 120W 3 In 1 Charging Cable USB Fast Charger...,phones-accessories,NaN,258.0,https://www.kilimall.co.ke/category/listing/27...
35,2M 10 inch Ring Light with Stand Tripod Live B...,phones-accessories,NaN,1299.0,https://www.kilimall.co.ke/category/listing/20...
36,2024 New 360 Rotation Gravity Car Phone Holder...,phones-accessories,NaN,350.0,https://www.kilimall.co.ke/category/listing/10...
37,PAFEL 2 in 1 OTG USB Adapter micro usb & Type ...,phones-accessories,NaN,159.0,https://www.kilimall.co.ke/category/listing/28...
38,The latest hot selling P9 Pro Max TWS micropho...,phones-accessories,NaN,599.0,https://www.kilimall.co.ke/category/listing/26...
39,JC pro3 TWS Wireless Bluetooth Earphone Stereo...,phones-accessories,NaN,459.0,https://www.kilimall.co.ke/category/listing/22...
40,Universal Foldable Stand Suitable for Mobile P...,phones-accessories,NaN,269.0,https://www.kilimall.co.ke/category/listing/10...
41,"Refurbished OPPO A57 F1 32GB+3GB 5.2 \"" 13MP+1...",phones-accessories,NaN,4399.0,https://www.kilimall.co.ke/category/listing/23...
42,"Refurbished oppo A5 /A3s Ram 4GB+Rom 64GB, Sma...",phones-accessories,NaN,6399.0,https://www.kilimall.co.ke/category/listing/26...
43,One factory TP Outdoor Bluetooth sunglasses wi...,phones-accessories,NaN,1499.0,https://www.kilimall.co.ke/category/listing/26...
44,"VR Glasses Virtual Reality Headset, Game/movie...",phones-accessories,NaN,1299.0,https://www.kilimall.co.ke/category/listing/10...
45,Multi-functional Retractable Mobile Phone Stan...,phones-accessories,NaN,329.0,https://www.kilimall.co.ke/category/listing/26...
46,2 In1 USB Wireless Bluetooth Adapter 5.0 Trans...,phones-accessories,NaN,449.0,https://www.kilimall.co.ke/category/listing/27...
47,Y30 TWS Wireless Earphones 5.0 Noise Cancellin...,phones-accessories,NaN,409.0,https://www.kilimall.co.ke/category/listing/22...
48,PAFEL omnidirectional metal microphone 3.5mm i...,phones-accessories,NaN,239.0,https://www.kilimall.co.ke/category/listing/24...
49,"Samsung Galaxy A05 64GB+4GB 50MP Camera 6.7\"" ...",phones-accessories,NaN,10850.0,https://www.kilimall.co.ke/category/listing/30...

In [29]:
# Convert 'price' column to integer
df["price"] = df["price"].astype(float)

In [30]:
df.dtypes

product_name            object
product_type            object
product_description    float64
price                  float64
link                    object
dtype: object

In [47]:
df['product_name'][5]

'Wireless Bluetooth Neckband Waterproof Sports Earphone with Sweatproof in-Ear Retractable Earbuds,Noise Cancelling Earphones For Workout, Running, Driving.'

In [37]:
#remove the pattern of anything enclosed in the brackets
df["product_name"] = df["product_name"].str.replace(r"【.*?】", "", regex=True).str.strip()