In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('corporate_law_data.csv')

In [ ]:
df.head()

,title,summary,content,links,url
0,Corporate law,Corporate law also known as company law or ent...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Chairman', '/wiki/Takeover_Code', '/wik...",https://en.wikipedia.org/wiki/Corporate_law
1,Corporation,,NA,'/wiki/Wikipedia:Protection_policy#pending',https://en.wikipedia.org/wiki/Corporation
2,Canadian corporate law,Canadian corporate law concerns the operation ...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Ontario', '/wiki/Series_LLC', '/wiki/Co...",https://en.wikipedia.org/wiki/Canadian_corpora...
3,Australian corporate law,Australian corporations law has historically b...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/BBY_Limited', '/wiki/Series_LLC', '/wik...",https://en.wikipedia.org/wiki/Australian_corpo...
4,Indian Corporate Law Service,The Indian Corporate Law Service Hindi abbrevi...,Amendment Basic structure doctrine Fundamental...,"'/wiki/District_Panchayat', '/wiki/List_of_sta...",https://en.wikipedia.org/wiki/Indian_Corporate...

In [27]:
# df.shape

df['content'][0]

'Anguilla\nAustralia\nBVI\nCanada\nCayman Islands\nIndia\nSouth Africa\nUK\nUnited States\nVietnam\nEuropean UnionFranceGermany\nFrance\nGermany\nFrance\nGermany\nCompany\nConglomerate\nCooperative\nCorporation\nHolding company\nJoint-stock\nPartnershipGeneralLimitedLimited liability\nGeneral\nLimited\nLimited liability\nPrivate limited\nShell corporation\nShelf corporation\nSole proprietorship\nGeneral\nLimited\nLimited liability\nSocietas(SE)\nSocietas cooperativa(SCE)\nSocietas privata(SPE)\nSocietas unius personae(SUP)\nEconomic interest grouping(EEIG)\nCharitable incorporated organisation\xa0(England and Wales)(CIO)\nScottish charitable incorporated organisation(SCIO)\nCommunity interest company(CIC)\nIndustrial and provident society(IPS)\nLimited company(Ltd.)by guaranteeby sharesproprietarypublic\nby guarantee\nby shares\nproprietary\npublic\nUnlimited company\nby guarantee\nby shares\nproprietary\npublic\nBenefit corporation\nC corporation\nLimited liability company(LLC)Low-profit LLC\nLow-profit LLC\nSeries LLC\nLimited liability limited partnership(LLLP)\nS corporation\nDelaware corporation/statutory trust\nMassachusetts business trust\nNevada corporation\nLow-profit LLC\nAktiebolag(AB)\nAktiengesellschaft(AG)\nAnsvarlig selskap(ANS)\nAktieselskab(A/S)\nAksjeselskap(AS)\nGesellschaft mit beschränkter Haftung(GmbH)\nKabushiki\xa0gaisha(K.K.)\nNaamloze vennootschap(N.V.)\nOsakeyhtiö(Oy)\nS.A.\nSociété à responsabilité limitée(SARL)\nmore...\nBusiness judgment rule\nCorporate governance\nDe factoand estoppel corporations\nInternal affairs doctrine\nLimited liability\nTag-along right\nDrag-along right\nPiercing the corporate veil\nRochdale Principles\nUltra vires\nBeneficial ownership\nCivil procedure\nContract\nCorporate registers\nRegistered agent\nCompany portal\nLaw portal\nv\nt\ne\nManagement accounting\nFinancial accounting\nAudit\nCorporate group\nCorporation sole\nCompany\nConglomerate\nHolding company\nCooperative\nCorporation\nJoint-stock company\nLimited liability company\nPartnership\nPrivately held company\nSole proprietorship\nState-owned enterprise\nAnnual general meeting\nBoard of directors\nSupervisory board\nAdvisory board\nAudit committee\nCommercial law\nConstitutional documents\nContract\nCorporate crime\nCorporate liability\nInsolvency law\nInternational trade law\nMergers and acquisitions\nChairman\nChief business officer/Chief brand officer\nChief executive officer/Chief operating officer\nChief financial officer\nChief human resources officer\nChief information officer/Chief marketing officer\nChief product officer/Chief technology officer\nCommodity\nPublic economics\nLabour economics\nDevelopment economics\nInternational economics\nMixed economy\nPlanned economy\nEconometrics\nEnvironmental economics\nOpen economy\nMarket economy\nKnowledge economy\nMicroeconomics\nMacroeconomics\nEconomic development\nEconomic statistics\nFinancial statement\nInsurance\nFactoring\nCash conversion cycle\nInsider dealing\nCapital budgeting\nCommercial bank\nDerivative\nFinancial statement analysis\nFinancial risk\nPublic finance\nCorporate finance\nManagerial finance\nInternational finance\nLiquidation\nStock market\nFinancial market\nTax\nFinancial institution\nCapital management\nVenture capital\nAsset\nBrand\nBusiness intelligence\nBusiness development\nCapacity\nCapability\nChangeinnovation\ninnovation\nCommercialMarketing\nMarketing\nCommunications\nConfiguration\nConflict\nContent\nCustomer relationship\nDistributed\nEarned value\nElectronic business\nEnterprise resource planningmanagement information system\nmanagement information system\nFinancial\nHuman resourcedevelopment\ndevelopment\nIncident\nKnowledge\nLegal\nMaterials\nNetworkadministrator\nadministrator\nOffice\nOperationsservices\nservices\nPerformance\nPower\nProcess\nProduct life-cycle\nProduct\nProject\nProperty\nQuality\nRecords\nResource\nRiskcrisis\ncrisis\nSales\nSecurity\nService\nStrategic\nSupply chain\nSystemsadministrator\nadministrator\nTalent\nTechnology\ninnovation\nMarketing\nmanagement information system\ndevelopment\nadministrator\nservices\ncrisis\nadministrator\nArchitecture\nBehavior\nCommunication\nCulture\nConflict\nDevelopment\nEngineering\nHierarchy\nPatterns\nSpace\nStructure\nBusiness analysis\nBusiness ethics\nBusiness plan\nBusiness judgment rule\nConsumer behaviour\nBusiness operations\nInternational business\nBusiness model\nInternational tradeTrade route\nTrade route\nBusiness process\nBusiness statistics\nTrade route\nBusiness and economics portal\nv\nt\ne\nImport\nExport\nBalance of trade\nTrade law\nTrade pact\nTrade bloc\nTrade creation\nTrade diversion\nExport orientation\nImport substitution\nTrade finance\nTrade facilitation\nTrade route\nDomestic trade\nTax\nTrade barriers\nTariffs\nNon-tariff barriers\nImport quotas\nTariff-rate quotas\nImport licenses\nCustoms duties\nExport subsidies\nTechnical barriers\nBribery\nExchange rate controls\nEmbargo\nSafeguards\nCountervailing duties\nAnti-dumping duties\nVoluntary export restraints\nMercantilism\nProtectionism\nLaissez-faire\nFree trade\nEconomic nationalism\nEconomic integration\nInternational Monetary Fund\nInternational Trade Centre\nWorld Trade Organization\nWorld Customs Organization\nInternational Chamber of Commerce\nPreferential trading area\nFree-trade area\nCurrency union\nCustoms union\nSingle market\nEconomic union\nFiscal union\nCustoms and monetary union\nEconomic and monetary union\nIntellectual property rights\nSmuggling\nCompetition policy\nGovernment procurement\nOutsourcing\nGlobalization\nFair trade\nTrade justice\nEmissions trading\nTrade sanctions\nWarCurrency warTrade costsTrade war\nCurrency war\nTrade costs\nTrade war\nTrade and development\nCurrency war\nTrade costs\nTrade war\nImports\nExports\nTariffs\nLargest consumer markets\nLeading trade partners\nTrade mission\nTrading nation\nUnited States\nArgentina\nPakistan\nRomania\nVietnam\nIndia\nComparative advantage\nCompetitive advantage\nHeckscher–Ohlin model\nNew trade theory\nEconomic geography\nIntra-industry trade\nGravity model of trade\nRicardian trade theories\nBalassa–Samuelson effect\nLinder hypothesis\nLeontief paradox\nLerner symmetry theorem\nTerms of trade\nv\nt\ne\nCorporate law(also known ascompany laworenterprise law) is the body oflawgoverning therights, relations, andconductofpersons,companies,organizationsandbusinesses. The term refers to the legal practice of law relating to corporations, or to the theory ofcorporations. Corporate law often describes the law relating to matters which derive directly from the life-cycle of a corporation.It thus encompasses the formation, funding, governance, and death of a corporation.\nWhile the minute nature of corporate governance as personified byshare ownership,capital market, andbusiness culturerules differ, similar legal characteristics and legal problems exist across many jurisdictions. Corporate law regulates howcorporations,investors,shareholders,directors,employees,creditors, and otherstakeholderssuch asconsumers, thecommunity, and theenvironmentinteract with one another.Whilst the termcompanyorbusiness lawis colloquially used interchangeably with corporate law, the termbusiness lawmostly refers to wider concepts ofcommercial law,that is the law relating to commercial and business related purposes and activities. In some cases, this may include matters relating tocorporate governanceorfinancial law. When used as a substitute for corporate law,business lawmeans the law relating to thebusiness corporation(or business enterprises), including such activity as raising capital, company formation, and registration with the government.\n\n=== Overview ===\n\nAcademics identify four legal characteristics universal to business enterprises. These are:\nSeparate legal personalityof the corporation (access to tort andcontract lawin a manner similar to a person)\nLimited liabilityof the shareholders (a shareholder\'s personal liability is limited to the value of their shares in the corporation)\nTransferable shares(if the corporation is a "public company", the shares are publicly listed and traded)\nDelegated managementunder a board structure; theboard of directorsdelegates day-to-day management of the company toexecutives.[1][2]\nWidely available and user-friendly corporate law enables business participants to possess these four legal characteristics and thus transact as businesses. Thus, corporate law is a response to three endemic opportunism: conflicts between managers and shareholders, between controlling and non-controlling shareholders; and between shareholders and other contractual counterparts (including creditors and employees).\nAcorporationmay accurately be called a company; however, a company should not necessarily be called a corporation, which has distinct characteristics. In the United States, a company may or may not be a separate legal entity, and is often used synonymous with "firm" or "business." According toBlack\'s Law Dictionary, in America a company means "a corporation — or, less commonly, an association, partnership or union — that carries on industrial enterprise."Other types of business associations can includepartnerships(in the UK governed by the Partnership Act 1890), ortrusts(such as a pension fund), or companies limited by guarantee (like some community organizations or charities). Corporate law deals with companies that are incorporated or registered under the corporate or company law of asovereign stateor theirsub-national states.\nThe defining feature of a corporation is its legal independence from the shareholders that own it. Under corporate law, corporations of all sizes haveseparate legal personality, withlimitedorunlimitedliability for its shareholders. Shareholders control the company through aboard of directorswhich, in turn, typically delegates control of the corporation\'s day-to-day operations to a full-timeexecutive. Shareholders\' losses, in the event of liquidation, are limited to their stake in the corporation, and they are not liable for any remaining debts owed to the corporation\'s creditors. This rule is calledlimited liability, and it is why the names of corporations end with "Ltd." or some variant such as "Inc." or "plc."\nUnder almost all legal systemscorporations have much the same legal rights and obligations as individuals. In some jurisdictions, this extends to allow corporations to exercisehuman rightsagainst real individuals and the state,and they may be responsible for human rights violations.Just as they are "born" into existence through its members obtaining acertificate of incorporation, they can "die" when they lose money intoinsolvency. Corporations can even be convicted of criminal offences, such ascorporate fraudandcorporate manslaughter.\n\n=== History ===\n\nAlthough some forms of companies are thought to have existed duringAncient RomeandAncient Greece, the closest recognizable ancestors of the modern company did not appear until the 16th century. With increasing international trade,Royal charterswere granted in Europe (notably inEnglandandHolland) to merchant adventurers.  The Royal charters usually conferred special privileges on the trading company (including, usually, some form ofmonopoly).  Originally, traders in these entities traded stock on their own account, but later the members came to operate on joint account and with joint stock, and the newJoint stock companywas born.\nEarly companies were purely economic ventures; it was only a belatedly established benefit of holding joint stock that the company\'s stock could not be seized for the debts of any individual member.The development of company law in Europe was hampered by two notorious "bubbles" (theSouth Sea Bubblein England and theTulip Bulb Bubblein theDutch Republic) in the 17th century, which set the development of companies in the two leading jurisdictions back by over a century in popular estimation.\nCompanies returned to the forefront of commerce, although in England to circumvent theBubble Act1720 investors had reverted to trading the stock of unincorporated associations, until it was repealed in 1825.However, the process of obtaining Royal charters was insufficient to keep up with demand.  In England there was a lively trade in the charters of defunct companies. It was not until theJoint Stock Companies Act 1844that the first equivalent of modern companies, formed by registration, appeared. Soon after came theLimited Liability Act 1855, which in the event of a company\'s bankruptcy limited the liability of all shareholders to the amount of capital they had invested.\nThe beginning of modern company law came when the two pieces of legislation were codified under theJoint Stock Companies Act 1856at the behest of the then Vice President of the Board of Trade, MrRobert Lowe. That legislation shortly gave way to the railway boom, and from there the numbers of companies formed soared. In the later nineteenth century depression took hold, and just as company numbers had boomed, many began to implode and fall into insolvency. Much strong academic, legislative and judicial opinion was opposed to the notion that businessmen could escape accountability for their role in the failing businesses. The last significant development in the history of companies was the decision of the House of Lords inSalomon v. Salomon & Co.where the House of Lords confirmed the separate legal personality of the company, and that the liabilities of the company were separate and distinct from those of its owners.\n\n=== Corporate structure ===\n\nThe law of business organizations originally derived from thecommon lawofEngland, and has evolved significantly in the 20th century. In common law countries today, the most commonly addressed forms are:\nCorporation\nLimited company\nUnlimited company\nLimited liability partnership\nLimited partnership\nNot-for-profit corporation\nCompany limited by guarantee\nPartnership\nSole proprietorship\nPrivately held company\nThe proprietary limited company is a statutory business form in several countries, includingAustralia. Many countries have forms of business entity unique to that country, although there are equivalents elsewhere. Examples are thelimited liability company(LLC) and thelimited liability limited partnership(LLLP) in the United States. Other types of business organizations, such ascooperatives,credit unionsand publicly owned enterprises, can be established with purposes that parallel, supersede, or even replace theprofit maximizationmandate of business corporations.\nThere are various types of company that can be formed in different jurisdictions, but the most common forms of company are:\nacompany limited by guarantee. Commonly used where companies are formed for non-commercial purposes, such as clubs or charities. The members guarantee the payment of certain (usually nominal) amounts if the company goes intoinsolvent liquidation, but otherwise they have no economic rights in relation to the company .\na company limited by guarantee with a share capital. A hybrid entity, usually used where the company is formed for non-commercial purposes, but the activities of the company are partly funded by investors who expect a return.\nacompany limited by shares. The most common form of company used for business ventures.\nanunlimited companyeither with or without a share capital. This is a hybrid company, a company similar to its limited company (Ltd.) counterpart but where the members or shareholders do not benefit from limited liability should the company ever go into formalliquidation.\nThere are, however, many specific categories of corporations and other business organizations which may be formed in various countries andjurisdictionsthroughout the world.\n\n=== Corporate legal personality ===\n\nOne of the key legal features of corporations are their separate legal personality, also known as "personhood" or being "artificial persons". However, the separate legal personality was not confirmed underEnglish lawuntil 1895 by theHouse of LordsinSalomon v. Salomon & Co.Separate legal personality often hasunintended consequences, particularly in relation to smaller,family companies. InB v. B[1978] Fam 181 it was held that adiscovery orderobtained by a wife against her husband was not effective against the husband\'s company as it was not named in the order and was separate and distinct from him.And inMacaura v. Northern Assurance Co Ltda claim under an insurance policy failed where the insured had transferred timber from his name into the name of a company wholly owned by him, and it was subsequently destroyed in a fire; as the property now belonged to the company and not to him, he no longer had an "insurable interest" in it and his claim failed.\nSeparate legal personality allows corporate groups flexibility in relation to tax planning, and management of overseas liability. For instance inAdams v. Cape Industries plcit was held that victims of asbestos poisoning at the hands of an American subsidiary could not sue the English parent in tort. Whilst academic discussion highlights certain specific situations where courts are generally prepared to "pierce the corporate veil", to look directly at, and impose liability directly on the individuals behind the company; the actual practice of piercing the corporate veil is, at English law, non-existent.However, the court will look beyond the corporate form where the corporation is a sham or perpetuating a fraud. The most commonly cited examples are:\nwhere the company is a mere façade\nwhere the company is effectively just the agent of its members or controllers\nwhere a representative of the company has taken some personal responsibility for a statement or action[14]\nwhere the company is engaged in fraud or other criminal wrongdoing\nwhere the natural interpretation of a contract or statute is as a reference to the corporate group and not the individual company\nwhere permitted by statute (for example, many jurisdictions provide for shareholder liability where a company breachesenvironmental protection laws)\nHistorically,  because companies are artificial persons created by operation of law, the law prescribed what the company could and could not do.  Usually this was an expression of the commercial purpose which the company was formed for, and came to be referred to as the company\'sobjects, and the extent of the objects are referred to as the company\'scapacity.  If an activity fell outside the company\'s capacity it was said to beultra viresandvoid.\nBy way of distinction, the organs of the company were expressed to have variouscorporate powers.  If the objects were the things that the company was able to do, then the powers were the means by which it could do them.  Usually expressions of powers were limited to methods of raising capital, although from earlier times distinctions between objects and powers have caused lawyers difficulty.Most jurisdictions have now modified the position by statute, and companies generally have capacity to do all the things that a natural person could do, and power to do it in any way that a natural person could do it.\nHowever, references to corporate capacity and powers have not quite been consigned to the dustbin of legal history.  In many jurisdictions, directors can still be liable to their shareholders if they cause the company to engage in businesses outside its objects, even if the transactions are still valid as between the company and the third party.  And many jurisdictions also still permit transactions to be challenged for lack of "corporate benefit", where the relevant transaction has no prospect of being for the commercial benefit of the company or its shareholders.\nAs artificial persons, companies can only act through human agents. The main agent who deals with the company\'s management and business is theboard of directors, but in many jurisdictions other officers can b

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9998 entries, 0 to 9997
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    9998 non-null   object
 1   summary  9102 non-null   object
 2   content  9107 non-null   object
 3   links    9998 non-null   object
 4   url      9998 non-null   object
dtypes: object(5)
memory usage: 390.7+ KB

In [6]:
missing_values = df.isnull()
missing_values.head()

   title  summary  content  links    url
0  False    False    False  False  False
1  False     True     True  False  False
2  False    False    False  False  False
3  False    False    False  False  False
4  False    False    False  False  False

In [7]:
for column in missing_values.columns.values.tolist():
    print(column)
    print (missing_values[column].value_counts())
    print("")

title
title
False    9998
Name: count, dtype: int64

summary
summary
False    9102
True      896
Name: count, dtype: int64

content
content
False    9107
True      891
Name: count, dtype: int64

links
links
False    9998
Name: count, dtype: int64

url
url
False    9998
Name: count, dtype: int64

In [14]:
df.dtypes

title      object
summary    object
content    object
links      object
url        object
dtype: object

In [86]:
#display the duplicate rows
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (1804, 5)

In [ ]:
#removing the duplicates

df = df.drop_duplicates()

In [118]:
#display the duplicate rows
duplicate_rows_df = df[df.duplicated()]
print("number of duplicate rows: ", duplicate_rows_df.shape)

number of duplicate rows:  (0, 6)

In [119]:
df.head()

,title,summary,content,links,url,Language
0,Corporate law,Corporate law also known as company law or ent...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Chairman', '/wiki/Takeover_Code', '/wik...",https://en.wikipedia.org/wiki/Corporate_law,en
1,Corporation,,NA,'/wiki/Wikipedia:Protection_policy#pending',https://en.wikipedia.org/wiki/Corporation,vi
2,Canadian corporate law,Canadian corporate law concerns the operation ...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Ontario', '/wiki/Series_LLC', '/wiki/Co...",https://en.wikipedia.org/wiki/Canadian_corpora...,en
3,Australian corporate law,Australian corporations law has historically b...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/BBY_Limited', '/wiki/Series_LLC', '/wik...",https://en.wikipedia.org/wiki/Australian_corpo...,en
4,Indian Corporate Law Service,The Indian Corporate Law Service Hindi abbrevi...,Amendment Basic structure doctrine Fundamental...,"'/wiki/District_Panchayat', '/wiki/List_of_sta...",https://en.wikipedia.org/wiki/Indian_Corporate...,en

In [87]:
#check for raw that have special characters
df['content'].str.contains('[^A-Za-z0-9 ]', regex=True).sum()

9107

In [28]:
dftrial = df

In [ ]:
dftrial["content"] = dftrial["content"].str.replace("\n", " ", regex=True)
dftrial["summary"] = dftrial["summary"].str.replace("\n", " ", regex=True)
dftrial["links"] = dftrial["links"].str.replace(r"\[", "", regex=True)
dftrial["links"] = dftrial["links"].str.replace(r"\]", "", regex=True)




dftrial.to_csv('mytrial.csv')

KeyboardInterrupt:

In [101]:
dftrial.head()

,title,summary,content,links,url
0,Corporate law,Corporate law also known as company law or ent...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Chairman', '/wiki/Takeover_Code', '/wik...",https://en.wikipedia.org/wiki/Corporate_law
1,Corporation,,NA,'/wiki/Wikipedia:Protection_policy#pending',https://en.wikipedia.org/wiki/Corporation
2,Canadian corporate law,Canadian corporate law concerns the operation ...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Ontario', '/wiki/Series_LLC', '/wiki/Co...",https://en.wikipedia.org/wiki/Canadian_corpora...
3,Australian corporate law,Australian corporations law has historically b...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/BBY_Limited', '/wiki/Series_LLC', '/wik...",https://en.wikipedia.org/wiki/Australian_corpo...
4,Indian Corporate Law Service,The Indian Corporate Law Service Hindi abbrevi...,Amendment Basic structure doctrine Fundamental...,"'/wiki/District_Panchayat', '/wiki/List_of_sta...",https://en.wikipedia.org/wiki/Indian_Corporate...

In [ ]:
# df['content'] = df['content'].apply(lambda x: translator.translate(x, dest='en').text)

NameError: name 'translator' is not defined

In [103]:
# # %pip install wordninja

# import pandas as pd
# import wordninja

# # Fill NaN values with an empty string
# dftrial['summary'] = dftrial['summary'].fillna('Not Available')
# dftrial['content'] = dftrial['content'].fillna('Not Available')



# # Apply word splitting
 dftrial['summary'] = dftrial['summary'].apply(lambda x: " ".join(wordninja.split(x)))
dftrial['content'] = dftrial['content'].apply(lambda x: " ".join(wordninja.split(x)))


# dftrial['summary'][0]

'Corporate law also known as company law or enterprise law is the body of law governing the rights relations and conduct of persons companies organizations and businesses The term refers to the legal practice of law relating to corporations or to the theory of corporations Corporate law often describes the law relating to matters which derive directly from the life cycle of a corporation 1 It thus encompasses the formation funding governance and death of a corporation While the minute nature of corporate governance as personified by share ownership capital market and business culture rules differ similar legal characteristics and legal problems exist across many jurisdictions Corporate law regulates how corporations investors shareholders directors employees creditors and other stakeholders such as consumers the community and the environment interact with one another 1 Whilst the term company or business law is colloquially used interchangeably with corporate law the term business law mostly refers to wider concepts of commercial law that is the law relating to commercial and business related purposes and activities In some cases this may include matters relating to corporate governance or financial law When used as a substitute for corporate law business law means the law relating to the business corporation or business enterprises including such activity as raising capital company formation and registration with the government'

In [122]:
dftrial.head()

,title,summary,content,links,url,Language
0,Corporate law,Corporate law also known as company law or ent...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Chairman', '/wiki/Takeover_Code', '/wik...",https://en.wikipedia.org/wiki/Corporate_law,en
1,Corporation,,NA,'/wiki/Wikipedia:Protection_policy#pending',https://en.wikipedia.org/wiki/Corporation,vi
2,Canadian corporate law,Canadian corporate law concerns the operation ...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Ontario', '/wiki/Series_LLC', '/wiki/Co...",https://en.wikipedia.org/wiki/Canadian_corpora...,en
3,Australian corporate law,Australian corporations law has historically b...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/BBY_Limited', '/wiki/Series_LLC', '/wik...",https://en.wikipedia.org/wiki/Australian_corpo...,en
4,Indian Corporate Law Service,The Indian Corporate Law Service Hindi abbrevi...,Amendment Basic structure doctrine Fundamental...,"'/wiki/District_Panchayat', '/wiki/List_of_sta...",https://en.wikipedia.org/wiki/Indian_Corporate...,en

In [108]:
%pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\lish\simba\simba-env\lib\site-packages (from deep-translator) (4.13.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\lish\simba\simba-env\lib\site-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\lish\simba\simba-env\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\lish\simba\simba-env\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lish\simba\simba-env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lish\simba\simba-env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lish\simba\simba-env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\lish\simba\simba-env\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.1.31)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4
Note: you may need to restart the kernel to use updated packages.

In [ ]:

from langdetect import detect
from deep_translator import GoogleTranslator


# Function to detect language
def detect_language(text):
    try:
        return detect(text)
    except:
        return "unknown"  # Handle errors

# Detect language
df['Language'] = df['content'].apply(detect_language)

# Filter only non-English rows
non_english_df = df[df['Language'] != 'en'].copy()  # Copy to avoid warnings

# Function to translate text
def translate_text(text):
    return GoogleTranslator(source='auto', target='en').translate(text)

# Apply translation **only to non-English rows**
non_english_df['EnglishText'] = non_english_df['EnglishText'].apply(translate_text)

# Merge back translated texts into original DataFrame
df.update(non_english_df)

# print(df)

In [112]:
%pip install langdetect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------------------------------------- 0.0/981.5 kB ? eta -:--:--
     ---------- ----------------------------- 262.1/981.5 kB ? eta -:--:--
     ---------- ----------------------------- 262.1/981.5 kB ? eta -:--:--
     ------------------- ---------------- 524.3/981.5 kB 612.9 kB/s eta 0:00:01
     ------------------- ---------------- 524.3/981.5 kB 612.9 kB/s eta 0:00:01
     ------------------- ---------------- 524.3/981.5 kB 612.9 kB/s eta 0:00:01
     ------------------- ---------------- 524.3/981.5 kB 612.9 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ---------------------------- ------- 786.4/981.5 kB 433.5 kB/s eta 0:00:01
     ------------------------------------ 981.5/981.5 kB 291.1 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: six in c:\users\lish\simba\simba-env\lib\site-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (pyproject.toml): started
  Building wheel for langdetect (pyproject.toml): finished with status 'done'
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993313 sha256=dbf407a3cd6a25e2a2d088d3bad158c5d21b5122e399eb64f3cdade3e4bf1ea3
  Stored in directory: c:\users\lish\appdata\local\pip\cache\wheels\eb\87\25\2dddf1c94e1786054e25022ec5530bfed52bad86d882999c48
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Note: you may need to restart the kernel to use updated packages.

In [116]:
df.to_csv('newthing.csv')

In [120]:
# drop columns language and EnglishText
df = df.drop(columns=['Language'])

In [121]:
df.head()

,title,summary,content,links,url
0,Corporate law,Corporate law also known as company law or ent...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Chairman', '/wiki/Takeover_Code', '/wik...",https://en.wikipedia.org/wiki/Corporate_law
1,Corporation,,NA,'/wiki/Wikipedia:Protection_policy#pending',https://en.wikipedia.org/wiki/Corporation
2,Canadian corporate law,Canadian corporate law concerns the operation ...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/Ontario', '/wiki/Series_LLC', '/wiki/Co...",https://en.wikipedia.org/wiki/Canadian_corpora...
3,Australian corporate law,Australian corporations law has historically b...,Anguilla Australia BVI Canada Cayman Islands I...,"'/wiki/BBY_Limited', '/wiki/Series_LLC', '/wik...",https://en.wikipedia.org/wiki/Australian_corpo...
4,Indian Corporate Law Service,The Indian Corporate Law Service Hindi abbrevi...,Amendment Basic structure doctrine Fundamental...,"'/wiki/District_Panchayat', '/wiki/List_of_sta...",https://en.wikipedia.org/wiki/Indian_Corporate...